language: php
php:
        - "7.0"

before_script:
        - composer self-update
        - composer install -d ./test/environment
        - git clone http://github.com/krakjoe/uopz uopz
        - cd uopz
        - phpize
        - ./configure
        - make
        - sudo make install
        - echo "extension=uopz.so" >> `php --ini | grep "Loaded Configuration" | sed "s/.*:\s*//"`
        - cd ..

script: phpunit --configuration ./build/config/unit.xml --bootstrap ./test/environment/Bootstrap.php
