language: php
php:
  - "5.4"

before-script:
 - pear channel-discover pear.bovigo.org
 - pear install bovigo/vfsStream-beta
 - phpenv rehash

script: phpunit --configuration ./build/config/php-unit.xml --bootstrap ./test/php/environment/Bootstrap.php