language: php
php:
        - "5.5"
        - "5.4"
        - "5.3"

before_script:
        - composer self-update
        - composer install -d ./test/environment
        - git clone http://github.com/zenovich/runkit.git runkit
        - cd runkit
        - phpize
        - ./configure
        - make
        - sudo make install
        - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed "s/.*:\s*//"`

script: phpunit --configuration ./build/config/unit.xml --bootstrap ./test/environment/Bootstrap.php
