language: php
php:
  - "5.4"

before-script:
  - composer update -d ./test/php/environment

script: phpunit --configuration ./build/config/php-unit.xml --bootstrap ./test/php/environment/Bootstrap.php