language: php
php:
  - "5.4"

before_script:
        - composer self-update
        - composer install -d ./test/environment

script: phpunit --configuration ./build/config/unit.xml --bootstrap ./test/environment/Bootstrap.php
