language: php
php:
  - "5.4"

before_script:
        - composer self-update
        - composer install -d ./test/php/environment

script: phpunit --configuration ./build/config/php-unit.xml --bootstrap ./test/php/environment/Bootstrap.php
